In [1]:
import numpy as np

In [2]:
array = np.array([1,7,13,105])

In [3]:
print(f"type:{type(array)}")
print(f"size:{array.size}")

type:<class 'numpy.ndarray'>
size:4


In [4]:
def fun(a):
    a1 =np.array([1,2,3,4,5])
    a2 =np.array([6,7,8,9,0])
    if a1[a]>a2[a]:
        print("a1 greater")
    elif a1[a]<a2[a]:
        print("a2 greater")
    else:
        print("equal")
    

In [5]:
fun(2)

a2 greater


In [6]:
fun(4)

a1 greater


In [7]:
def fun1():
    array =np.zeros(10)
    a1=np.ones(10)
    a2=np.ones(10)*5
    a3=np.ones(10)*10
    a4=np.ones(10)*20
    a5=np.ones(10)*50
    print(array,a1,a2,a3,a4,a5)
    

In [8]:
fun1()

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.] [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.] [20. 20. 20. 20. 20. 20. 20. 20. 20. 20.] [50. 50. 50. 50. 50. 50. 50. 50. 50. 50.]


In [9]:
array=np.arange(30,71,1)
array1=np.arange(50,96,1)
print(array,array1)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70] [50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95]


In [10]:
array=np.arange(20,80,2)
print(array)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78]


In [11]:
array=np.arange(21,80,2)
print(array)

[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71 73 75 77 79]


In [12]:
array=np.random.randint(10,40,15)
print(array)

[19 13 32 39 36 13 28 13 14 37 24 25 28 32 25]


In [13]:
array=np.random.randint(30,50,10)
print(array)

[41 40 40 47 41 36 37 32 45 44]


In [14]:
array=np.random.randint(50,90,20)
print(array)

[52 81 57 55 56 50 63 50 82 78 71 82 57 57 71 84 87 87 88 55]


In [15]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([9,8,7,6,0])
print((arr1+arr2),(arr1-arr2),(arr1*arr2),(arr1/arr2))

[10 10 10 10  5] [-8 -6 -4 -2  5] [ 9 16 21 24  0] [0.11111111 0.25       0.42857143 0.66666667        inf]


/tmp/ipykernel_17545/3102313400.py:3: RuntimeWarning: divide by zero encountered in divide
  print((arr1+arr2),(arr1-arr2),(arr1*arr2),(arr1/arr2))


In [16]:
arr1=np.arange(10,22,1)
arr1=arr1.reshape(3,4)
print(arr1)


[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [17]:
arr1=np.eye(3)
#arr1=arr1.reshape(3,3)

print(arr1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
arr1=np.arange(10,19,1)
arr1=arr1.reshape(3,3)
dimensions=arr1.shape
rows,coloum=dimensions
print(dimensions)


(3, 3)


In [19]:
arr=np.diag([1,2,3,4,5])
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [20]:
arr=np.random.rand(3,3,3)
print(arr)

[[[0.83430568 0.9253665  0.22630154]
  [0.27582573 0.12306611 0.85495596]
  [0.78247099 0.78748138 0.32616942]]

 [[0.90676579 0.08534848 0.65968638]
  [0.29411802 0.4045212  0.63729469]
  [0.87082996 0.03806309 0.28482837]]

 [[0.9134478  0.96533415 0.91794361]
  [0.63579561 0.15980002 0.59509058]
  [0.34475221 0.59615271 0.43605008]]]


In [21]:
arr=np.random.rand(2,3,4)
print(arr)

[[[0.33211109 0.86029193 0.39772945 0.78327503]
  [0.94703902 0.15294646 0.2998508  0.9458313 ]
  [0.65821539 0.16035085 0.23628286 0.91890853]]

 [[0.12003847 0.90663603 0.98322704 0.99595746]
  [0.61042479 0.52146934 0.42343427 0.18027214]
  [0.75288675 0.90260484 0.73834527 0.97747257]]]


In [22]:
l1=[1,2,3,4,5]
arr=np.array(l1)
print(arr)

[1 2 3 4 5]


In [23]:
l1=np.arange(2,11).reshape(3,3)
print(l1)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [24]:
l1=np.arange(12,38)

print(l1)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [25]:
l1=np.arange(12,38)
print(l1[::-1])

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [26]:
arr=np.array([1,2,3,4,5],dtype=float)
print(f"dtype={arr.dtype}")

dtype=float64


In [27]:
l1=[1,2,3,4,5]
arr=np.array(l1)
print(arr)

[1 2 3 4 5]


In [28]:
a=np.arange(8)
print(np.remainder(a,2))

[0 1 0 1 0 1 0 1]


In [32]:
a=np.arange(20,50)
print(np.remainder(a,3))


[2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1]
